spring:
  datasource:
    url: jdbc:mysql://localhost:3307/camunda_db?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: camunda
    password: camunda
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://keycloak.kuberthay.pro/realms/poc-domnerka
        registration:
          keycloak:
            client-id: camunda-identity-service
            client-secret: WnOXRottiilGLBK1uDQUEs7uowZZ64Fz
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/keycloak"
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.kuberthay.pro/realms/poc-domnerka
          jwk-set-uri: https://keycloak.kuberthay.pro/realms/poc-domnerka/protocol/openid-connect/certs

camunda.bpm:
  database:
    schema-update: false
  authorization:
    enabled: true
  history-level: full
  generic-properties:
    properties:
      historyTimeToLive: 1095
      history-cleanup-enabled: false

plugin.identity.keycloak:
  keycloakIssuerUrl: https://keycloak.kuberthay.pro/realms/poc-domnerka
  keycloakAdminUrl: https://keycloak.kuberthay.pro/admin/realms/poc-domnerka
  clientId: camunda-identity-service
  clientSecret: WnOXRottiilGLBK1uDQUEs7uowZZ64Fz
  useUsernameAsCamundaUserId: true
  administratorGroupName: camunda-admin
  disableSSLCertificateValidation: false
  realm: poc-domnerka
  enforceSubgroupsInGroupQuery: true

cors:
  allowed-origins: http://localhost:5173/

keycloak:
  base-url: https://keycloak.kuberthay.pro